spring:
  application:
    name: prova-dixi-api
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password
  jpa:
    database-plaform: "org.hibernate.dialect.H2Dialect"
  h2:
    console-enabled: true
